// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agentmgmt.proto

/*
Package grpc_types is a generated protocol buffer package.

It is generated from these files:
	agentmgmt.proto
	globalapi.proto
	hello.proto
	world.proto

It has these top-level messages:
	GetAvailableAgentsRequest
	GetAvailableAgentsResponse
	HelloRequest
	HelloResponse
	WorldRequest
	WorldResponse
*/
package grpc_types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAvailableAgentsRequest struct {
	Limit int32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetAvailableAgentsRequest) Reset()                    { *m = GetAvailableAgentsRequest{} }
func (m *GetAvailableAgentsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAvailableAgentsRequest) ProtoMessage()               {}
func (*GetAvailableAgentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetAvailableAgentsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetAvailableAgentsResponse struct {
	AgentIds []string `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds" json:"agent_ids,omitempty"`
}

func (m *GetAvailableAgentsResponse) Reset()                    { *m = GetAvailableAgentsResponse{} }
func (m *GetAvailableAgentsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAvailableAgentsResponse) ProtoMessage()               {}
func (*GetAvailableAgentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetAvailableAgentsResponse) GetAgentIds() []string {
	if m != nil {
		return m.AgentIds
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAvailableAgentsRequest)(nil), "grpc_types.GetAvailableAgentsRequest")
	proto.RegisterType((*GetAvailableAgentsResponse)(nil), "grpc_types.GetAvailableAgentsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AgentMgmt service

type AgentMgmtClient interface {
	// AgentMgmt service // Go uses CamelCase so use it for API calls
	GetAvailableAgents(ctx context.Context, in *GetAvailableAgentsRequest, opts ...grpc.CallOption) (*GetAvailableAgentsResponse, error)
}

type agentMgmtClient struct {
	cc *grpc.ClientConn
}

func NewAgentMgmtClient(cc *grpc.ClientConn) AgentMgmtClient {
	return &agentMgmtClient{cc}
}

func (c *agentMgmtClient) GetAvailableAgents(ctx context.Context, in *GetAvailableAgentsRequest, opts ...grpc.CallOption) (*GetAvailableAgentsResponse, error) {
	out := new(GetAvailableAgentsResponse)
	err := grpc.Invoke(ctx, "/grpc_types.AgentMgmt/GetAvailableAgents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentMgmt service

type AgentMgmtServer interface {
	// AgentMgmt service // Go uses CamelCase so use it for API calls
	GetAvailableAgents(context.Context, *GetAvailableAgentsRequest) (*GetAvailableAgentsResponse, error)
}

func RegisterAgentMgmtServer(s *grpc.Server, srv AgentMgmtServer) {
	s.RegisterService(&_AgentMgmt_serviceDesc, srv)
}

func _AgentMgmt_GetAvailableAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentMgmtServer).GetAvailableAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_types.AgentMgmt/GetAvailableAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentMgmtServer).GetAvailableAgents(ctx, req.(*GetAvailableAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentMgmt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_types.AgentMgmt",
	HandlerType: (*AgentMgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableAgents",
			Handler:    _AgentMgmt_GetAvailableAgents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agentmgmt.proto",
}

func init() { proto.RegisterFile("agentmgmt.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4c, 0x4f, 0xcd,
	0x2b, 0xc9, 0x4d, 0xcf, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x2f, 0x2a,
	0x48, 0x8e, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x56, 0x32, 0xe4, 0x92, 0x74, 0x4f, 0x2d, 0x71, 0x2c,
	0x4b, 0xcc, 0xcc, 0x49, 0x4c, 0xca, 0x49, 0x75, 0x04, 0x29, 0x2d, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0xc9, 0xcc, 0xcd, 0x2c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0x82, 0x70, 0x94, 0x2c, 0xb9, 0xa4, 0xb0, 0x69, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x15, 0x92, 0xe6, 0xe2, 0x04, 0xdb, 0x17, 0x9f, 0x99, 0x52, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1,
	0x19, 0xc4, 0x01, 0x16, 0xf0, 0x4c, 0x29, 0x36, 0x2a, 0xe2, 0xe2, 0x04, 0x2b, 0xf7, 0x4d, 0xcf,
	0x2d, 0x11, 0x4a, 0xe5, 0x12, 0xc2, 0x34, 0x47, 0x48, 0x55, 0x0f, 0xe1, 0x3a, 0x3d, 0x9c, 0x4e,
	0x93, 0x52, 0x23, 0xa4, 0x0c, 0xe2, 0x1c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xa7, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xca, 0x85, 0xb1, 0xc8, 0x07, 0x01, 0x00, 0x00,
}
