// Code generated by protoc-gen-go. DO NOT EDIT.
// source: globalapi.proto

/*
Package grpc_types is a generated protocol buffer package.

It is generated from these files:
	globalapi.proto
	hello.proto
	world.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
	WorldRequest
	WorldResponse
*/
package grpc_types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import grpc_types1 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GlobalAPI service

type GlobalAPIClient interface {
	// All API calls from all services
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	SayWorld(ctx context.Context, in *WorldRequest, opts ...grpc.CallOption) (*WorldResponse, error)
	GetAvailableAgents(ctx context.Context, in *grpc_types1.GetAvailableAgentsRequest, opts ...grpc.CallOption) (*grpc_types1.GetAvailableAgentsResponse, error)
}

type globalAPIClient struct {
	cc *grpc.ClientConn
}

func NewGlobalAPIClient(cc *grpc.ClientConn) GlobalAPIClient {
	return &globalAPIClient{cc}
}

func (c *globalAPIClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/grpc_types.GlobalAPI/sayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalAPIClient) SayWorld(ctx context.Context, in *WorldRequest, opts ...grpc.CallOption) (*WorldResponse, error) {
	out := new(WorldResponse)
	err := grpc.Invoke(ctx, "/grpc_types.GlobalAPI/sayWorld", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalAPIClient) GetAvailableAgents(ctx context.Context, in *grpc_types1.GetAvailableAgentsRequest, opts ...grpc.CallOption) (*grpc_types1.GetAvailableAgentsResponse, error) {
	out := new(grpc_types1.GetAvailableAgentsResponse)
	err := grpc.Invoke(ctx, "/grpc_types.GlobalAPI/GetAvailableAgents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GlobalAPI service

type GlobalAPIServer interface {
	// All API calls from all services
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	SayWorld(context.Context, *WorldRequest) (*WorldResponse, error)
	GetAvailableAgents(context.Context, *grpc_types1.GetAvailableAgentsRequest) (*grpc_types1.GetAvailableAgentsResponse, error)
}

func RegisterGlobalAPIServer(s *grpc.Server, srv GlobalAPIServer) {
	s.RegisterService(&_GlobalAPI_serviceDesc, srv)
}

func _GlobalAPI_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalAPIServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_types.GlobalAPI/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalAPIServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalAPI_SayWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalAPIServer).SayWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_types.GlobalAPI/SayWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalAPIServer).SayWorld(ctx, req.(*WorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalAPI_GetAvailableAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(grpc_types1.GetAvailableAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalAPIServer).GetAvailableAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_types.GlobalAPI/GetAvailableAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalAPIServer).GetAvailableAgents(ctx, req.(*grpc_types1.GetAvailableAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GlobalAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_types.GlobalAPI",
	HandlerType: (*GlobalAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sayHello",
			Handler:    _GlobalAPI_SayHello_Handler,
		},
		{
			MethodName: "sayWorld",
			Handler:    _GlobalAPI_SayWorld_Handler,
		},
		{
			MethodName: "GetAvailableAgents",
			Handler:    _GlobalAPI_GetAvailableAgents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "globalapi.proto",
}

func init() { proto.RegisterFile("globalapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcf, 0xc9, 0x4f,
	0x4a, 0xcc, 0x49, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x2f, 0x2a,
	0x48, 0x8e, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x96, 0xe2, 0xce, 0x48, 0xcd, 0xc9, 0xc9, 0x87, 0x48,
	0x48, 0x71, 0x97, 0xe7, 0x17, 0xe5, 0xa4, 0x40, 0x39, 0xfc, 0x89, 0xe9, 0xa9, 0x79, 0x25, 0xb9,
	0xe9, 0xb9, 0x25, 0x10, 0x01, 0xa3, 0x1f, 0x8c, 0x5c, 0x9c, 0xee, 0x60, 0xa3, 0x1c, 0x03, 0x3c,
	0x85, 0x1c, 0xb9, 0x38, 0x8a, 0x13, 0x2b, 0x3d, 0x40, 0xba, 0x85, 0x24, 0xf4, 0x10, 0x26, 0xea,
	0x81, 0x85, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xa4, 0x24, 0xb1, 0xc8, 0x14, 0x17, 0xe4,
	0xe7, 0x15, 0xa7, 0x2a, 0x31, 0x40, 0x8d, 0x08, 0x07, 0xd9, 0x89, 0x6a, 0x04, 0x58, 0x08, 0xab,
	0x11, 0x50, 0x19, 0xb8, 0x11, 0xa9, 0x5c, 0x42, 0xee, 0xa9, 0x25, 0x8e, 0x65, 0x89, 0x99, 0x39,
	0x89, 0x49, 0x39, 0xa9, 0x8e, 0x20, 0x27, 0x17, 0x0b, 0xa9, 0x22, 0x6b, 0xc1, 0x94, 0x87, 0x99,
	0xac, 0x46, 0x48, 0x19, 0xcc, 0x9a, 0x24, 0x36, 0x70, 0x08, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xb9, 0x7f, 0x2a, 0x99, 0x4b, 0x01, 0x00, 0x00,
}
