# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agentmgmt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agentmgmt.proto',
  package='grpc_types',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x61gentmgmt.proto\x12\ngrpc_types\"\x1b\n\x19GetAvailableAgentsRequest\"/\n\x1aGetAvailableAgentsResponse\x12\x11\n\tagent_ids\x18\x01 \x03(\t2r\n\tAgentMgmt\x12\x65\n\x12GetAvailableAgents\x12%.grpc_types.GetAvailableAgentsRequest\x1a&.grpc_types.GetAvailableAgentsResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETAVAILABLEAGENTSREQUEST = _descriptor.Descriptor(
  name='GetAvailableAgentsRequest',
  full_name='grpc_types.GetAvailableAgentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=58,
)


_GETAVAILABLEAGENTSRESPONSE = _descriptor.Descriptor(
  name='GetAvailableAgentsResponse',
  full_name='grpc_types.GetAvailableAgentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_ids', full_name='grpc_types.GetAvailableAgentsResponse.agent_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['GetAvailableAgentsRequest'] = _GETAVAILABLEAGENTSREQUEST
DESCRIPTOR.message_types_by_name['GetAvailableAgentsResponse'] = _GETAVAILABLEAGENTSRESPONSE

GetAvailableAgentsRequest = _reflection.GeneratedProtocolMessageType('GetAvailableAgentsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETAVAILABLEAGENTSREQUEST,
  __module__ = 'agentmgmt_pb2'
  # @@protoc_insertion_point(class_scope:grpc_types.GetAvailableAgentsRequest)
  ))
_sym_db.RegisterMessage(GetAvailableAgentsRequest)

GetAvailableAgentsResponse = _reflection.GeneratedProtocolMessageType('GetAvailableAgentsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETAVAILABLEAGENTSRESPONSE,
  __module__ = 'agentmgmt_pb2'
  # @@protoc_insertion_point(class_scope:grpc_types.GetAvailableAgentsResponse)
  ))
_sym_db.RegisterMessage(GetAvailableAgentsResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class AgentMgmtStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetAvailableAgents = channel.unary_unary(
          '/grpc_types.AgentMgmt/GetAvailableAgents',
          request_serializer=GetAvailableAgentsRequest.SerializeToString,
          response_deserializer=GetAvailableAgentsResponse.FromString,
          )


  class AgentMgmtServicer(object):

    def GetAvailableAgents(self, request, context):
      """AgentMgmt service // Go uses CamelCase so use it for API calls
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_AgentMgmtServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetAvailableAgents': grpc.unary_unary_rpc_method_handler(
            servicer.GetAvailableAgents,
            request_deserializer=GetAvailableAgentsRequest.FromString,
            response_serializer=GetAvailableAgentsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'grpc_types.AgentMgmt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaAgentMgmtServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetAvailableAgents(self, request, context):
      """AgentMgmt service // Go uses CamelCase so use it for API calls
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaAgentMgmtStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetAvailableAgents(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """AgentMgmt service // Go uses CamelCase so use it for API calls
      """
      raise NotImplementedError()
    GetAvailableAgents.future = None


  def beta_create_AgentMgmt_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('grpc_types.AgentMgmt', 'GetAvailableAgents'): GetAvailableAgentsRequest.FromString,
    }
    response_serializers = {
      ('grpc_types.AgentMgmt', 'GetAvailableAgents'): GetAvailableAgentsResponse.SerializeToString,
    }
    method_implementations = {
      ('grpc_types.AgentMgmt', 'GetAvailableAgents'): face_utilities.unary_unary_inline(servicer.GetAvailableAgents),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_AgentMgmt_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('grpc_types.AgentMgmt', 'GetAvailableAgents'): GetAvailableAgentsRequest.SerializeToString,
    }
    response_deserializers = {
      ('grpc_types.AgentMgmt', 'GetAvailableAgents'): GetAvailableAgentsResponse.FromString,
    }
    cardinalities = {
      'GetAvailableAgents': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'grpc_types.AgentMgmt', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
