# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: globalapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import hello_pb2 as hello__pb2
import world_pb2 as world__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='globalapi.proto',
  package='hello',
  syntax='proto3',
  serialized_pb=_b('\n\x0fglobalapi.proto\x12\x05hello\x1a\x0bhello.proto\x1a\x0bworld.protob\x06proto3')
  ,
  dependencies=[hello__pb2.DESCRIPTOR,world__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
