# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ping_pb2 as ping__pb2


class PingStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/grpc_types.Ping/Ping',
        request_serializer=ping__pb2.PingRequest.SerializeToString,
        response_deserializer=ping__pb2.PingResponse.FromString,
        )


class PingServicer(object):

  def Ping(self, request, context):
    """Go uses CamelCase so use it for API calls
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=ping__pb2.PingRequest.FromString,
          response_serializer=ping__pb2.PingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_types.Ping', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
