# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='world.proto',
  package='grpc_types',
  syntax='proto3',
  serialized_pb=_b('\n\x0bworld.proto\x12\ngrpc_types\"\x1f\n\x0cWorldRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rWorldResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2J\n\x05World\x12\x41\n\x08sayWorld\x12\x18.grpc_types.WorldRequest\x1a\x19.grpc_types.WorldResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WORLDREQUEST = _descriptor.Descriptor(
  name='WorldRequest',
  full_name='grpc_types.WorldRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc_types.WorldRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=58,
)


_WORLDRESPONSE = _descriptor.Descriptor(
  name='WorldResponse',
  full_name='grpc_types.WorldResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc_types.WorldResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['WorldRequest'] = _WORLDREQUEST
DESCRIPTOR.message_types_by_name['WorldResponse'] = _WORLDRESPONSE

WorldRequest = _reflection.GeneratedProtocolMessageType('WorldRequest', (_message.Message,), dict(
  DESCRIPTOR = _WORLDREQUEST,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:grpc_types.WorldRequest)
  ))
_sym_db.RegisterMessage(WorldRequest)

WorldResponse = _reflection.GeneratedProtocolMessageType('WorldResponse', (_message.Message,), dict(
  DESCRIPTOR = _WORLDRESPONSE,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:grpc_types.WorldResponse)
  ))
_sym_db.RegisterMessage(WorldResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class WorldStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.sayWorld = channel.unary_unary(
          '/grpc_types.World/sayWorld',
          request_serializer=WorldRequest.SerializeToString,
          response_deserializer=WorldResponse.FromString,
          )


  class WorldServicer(object):

    def sayWorld(self, request, context):
      """World service 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_WorldServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'sayWorld': grpc.unary_unary_rpc_method_handler(
            servicer.sayWorld,
            request_deserializer=WorldRequest.FromString,
            response_serializer=WorldResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'grpc_types.World', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaWorldServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def sayWorld(self, request, context):
      """World service 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaWorldStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def sayWorld(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """World service 
      """
      raise NotImplementedError()
    sayWorld.future = None


  def beta_create_World_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('grpc_types.World', 'sayWorld'): WorldRequest.FromString,
    }
    response_serializers = {
      ('grpc_types.World', 'sayWorld'): WorldResponse.SerializeToString,
    }
    method_implementations = {
      ('grpc_types.World', 'sayWorld'): face_utilities.unary_unary_inline(servicer.sayWorld),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_World_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('grpc_types.World', 'sayWorld'): WorldRequest.SerializeToString,
    }
    response_deserializers = {
      ('grpc_types.World', 'sayWorld'): WorldResponse.FromString,
    }
    cardinalities = {
      'sayWorld': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'grpc_types.World', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
